[project]
# 用户请勿编辑
name = "fexgame"
version = "1.0.1"
description = "This is a game made by Fex Studio."
author = ['fxbd5684']
email = "2734664632@qq.com"
url = "http://www.github.com/fxbd5684/fexgame"

[new]
what = """
version 1.0.1
- 添加提升暴击率功能
"""

[update]
'v 1.0.0' = """
完成用户属性提升功能

- 修复对战时对手攻击使用用户属性的BUG
- 添加ucf功能
- 添加项目编译pyc的模块

希望下次修改(添加):
    1. 用户提升后,战斗伤害增加不明显,伤害只多零点几,没有继续升级的动力
    2. 希望下次添加冥想技能功能
    3. 对手生成算法有待改进,希望加入更大的随机率
"""

'v 0.1.1' = """
完成暴击与奖励系统

更新底层用户模型
增加暴击率与战斗积分
"""

'v 0.1.0' = """
成战斗功能
庆祝代码突破100行!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

最难写的战斗功能终于tmd写完了
脑子要废了

建议后期添加的功能如下:
    1. 暴击功能,这可能需要修改底层用户模型,还好我们还在开发阶段,这些还很好改
    2. 奖励结算功能,用户赢了,我们应该给用户一些奖励
"""

'v 0.0.0' = """
项目开始

- 完成基本框架
"""
