name: 构建并上传游戏
on: push

permissions:
  contents: write

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 安装PyInstaller
        run: |
          pip3 install pyinstaller
      - name: 编译Linux版本
        run: |
          pyinstaller -D --clean --distpath dist/linux/ main.py

  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 安装PyInstaller
        run: |
          pip install pyinstaller
      - name: 编译Windows版本
        run: |
          pyinstaller -D --clean --distpath dist\windows\ main.py

  deploy:
    runs-on: ubuntu-latest
    needs: [build-on-linux, build-on-windows]
    steps:
      - name: commit
        run: |
          git config --global user.email 2734664632@qq.com
          git config --global user.name fxbd5684
          git add .
          git commit -m "update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
