name: 构建并上传游戏

on: push

jobs:

  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 安装PyInstaller
        run: |
          pip3 install pyinstaller
      - name: 编译Linux版本
        run: |
          pyinstaller -D --clean --distpath dist/linux/ main.py
      - name: 上传Linux构建工件
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/linux/

  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 安装PyInstaller
        run: |
          pip install pyinstaller
      - name: 编译Windows版本
        run: |
          pyinstaller -D --clean --distpath dist\windows\ main.py
      - name: 上传Windows构建工件
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist\windows\