name: fexgame

on: push

jobs:

  copy_files_to_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  build-on-linux:
    runs-on: ubuntu-latest
    needs: copy_files_to_vm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: pyinstaller
        run: |
          pip3 install pyinstaller
      - name: 编译
        run: |
          pyinstaller -D --clean --distpath dist\linux\ main.py

  build-on-windows:
    runs-on: windows-latest
    needs: copy_files_to_vm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: pyinstaller
        run: |
          pip install pyinstaller
      - name: 编译
        run: |
          pyinstaller -D --clean --distpath dist\windows\ main.py