name: fexgame

on: push

jobs:
  拷贝文件到虚拟机:
    runs-on: ubuntu-latest
    steps:
      - name: 拷贝文件
        uses: actions/checkout@v1

  build-on-linux:
    runs-on: ubuntu-latest
    needs: 拷贝文件到虚拟机
    steps:
      - name: pyinstaller
        run: |
          pip3 install pyinstaller
      - name: 编译
        run: |
          pyinstaller -D --clean --distpath dist\linux\ main.py

  build-on-windows:
    runs-on: windows-latest
    needs: 拷贝文件到虚拟机
    steps:
      - name: pyinstaller
        run: |
          pip install pyinstaller
      - name: 编译
        run: |
          pyinstaller -D --clean --distpath dist\windows\ main.py
