name: Build and Package

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Package with PyInstaller
      run: |
        pyinstaller -D main.py
        rm -r build
        
    - name: Commit packaged files
      run: |
        git config --global user.name "fxbd5684"
        git config --global user.email "2734664632@qq.com"
        git checkout -b build
        git add dist
        git commit -m "Add packaged files to build branch"
        git push origin build --force